import Head from 'next/head'
import Skills from '../src/Skills/Skills'
import Title from '../src/Title/Title'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gulay Jabrailzade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className={styles.main}>
        <Title />
        <Skills />
      </div>


    </div>
  )
}
